```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

# Other packages {#other-packages}

## packages taxize leverages {#taxize-built-on}

There's a number of packages that `taxize` builds on:

* [bold](#package-bold)
* [rredlist](#package-rredlist)
* [rotl](#package-rotl)
* [ritis](#package-ritis)
* [worrms](#package-worrms)
* [natserv](#package-natserv)
* [wikitaxa](#package-wikitaxa)

You can use these packages individually if you're only interested
in the data from that one data source. Furthermore, each of these packages
has more functionality for dealing with that specific data source. The 
benefit of using `taxize` is that it attemps to make a more consistent 
interface across the different data sources.

### package: bold {#package-bold}

The [bold][] package interfaces with [BOLD Systems](http://boldsystems.org/) which hosts
barcoding data, and includes taxonomic information.


### package: rredlist {#package-rredlist}

The [rredlist][] package interfaces with [IUCN Red List of Threatened Species](http://www.iucnredlist.org/).
They have various kinds of data around the life history of the various threatneed
species, including taxonomic information.

> Important: An API key is required for this package. Request one at <http://apiv3.iucnredlist.org/api/v3/token>. It is not unusual to have to wait many weeks to get your key.


### package: rotl {#package-rotl}

The [rotl][] package interfaces with the [Open Tree of Life](https://tree.opentreeoflife.org/),
curating an open phylogenetic tree of all life.

### package: ritis {#package-ritis}

The [ritis][] package interfaces with the
[Integrated Taxonomic Information Service](https://www.itis.gov/), taxonomic information on plants,
animals, fungi, and microbes of North America and the world.

### package: worrms {#package-worrms}

The [worrms][] package interfaces with the [World Register of Marine Species](http://www.marinespecies.org/),
an authoritative classifcation and catalogue of marine names.

### package: natserv {#package-natserv}

The [natserv][] package interfaces with the [NatureServe](https://services.natureserve.org/),
a biodiversity database.


### package: wikitaxa {#package-wikitaxa}

The [wikitaxa][] package interfaces with [Wikispecies](https://species.wikimedia.org/wiki/Main_Page),
[Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page), and [Wikipedia](https://www.wikipedia.org/),
facilitating extraction of taxonomic name information from each site.


## related packages {#related-packages}

[taxizesoap][] is no longer maintained. It was maintained for a number of years,
with functionality for handling web services that used the [SOAP protocol][soap],
an older web service protocol that has been largeley replaced with other protocols.
Most if not all data sources that were in taxizesoap have been moved to taxize.


[bold]: https://github.com/ropensci/bold
[rredlist]: https://github.com/ropensci/rredlist
[rotl]: https://github.com/ropensci/rotl
[ritis]: https://github.com/ropensci/ritis
[worrms]: https://github.com/ropensci/worrms
[natserv]: https://github.com/ropensci/natserv
[wikitaxa]: https://github.com/ropensci/wikitaxa
[taxizesoap]: https://github.com/ropensci/taxizesoap
[soap]: https://en.wikipedia.org/wiki/SOAP
